########################################################
# Husarion Use Case
########################################################

# List of topics that the DDS Router will forward.
# Any topic not included in this list will be blocked by the DDS Router.
# This list can be updated at run time.
allowlist:
  - name: "rt/chatter"
    type: "std_msgs::msg::dds_::String_"

IntraRobotParticipant:
  type: local
  domain: 0

EchoParticipant:
  type: echo

InterRobotParticipant:
  type: wan
  id: 110
  
  connection-addresses:
    - guid: "44.53.01.5f.45.50.52.4f.53.49.4d.41"
      addresses:
        - ip: "dds-discovery-server" #discovery-server
          port: 11811
          transport: "udp6"