########################################################
# Husarion Use Case
########################################################

# List of topics that the DDS Router will forward.
# Any topic not included in this list will be blocked by the DDS Router.
# This list can be updated at run time.
allowlist:
  [
    {
      name: "rt/chatter", 
      type: "std_msgs::msg::dds_::String_"
    },
    {
      name: "HelloWorldTopic", 
      type: "HelloWorld"
    }
  ]

# Participant responsible for subscribing and publishing in the internal topics of the robot.
# This participant implements the Simple discovery protocol.
IntraRobotParticipant:
  type: local
  domain: 0

# InterRobotParticipant:
#   type: "wan"
#   id: 1
#   # Network address of the DS-Server to which the robots connect.
#   listening-addresses:
#   [
#     {
#       ip: "fc94:1c77:2f76:b88e:464d:84ad:471f:7dce", 
#       port: 11811,
#     },
#   ]


InterRobotParticipant:
  type: local-discovery-server
  id: 324
  # Network address of the DS-Server to which the robots connect.
  connection-addresses:
  [
    {
      id: 1, # This is equivalent to: guid: "44.53.01.5f.45.50.52.4f.53.49.4d.41"
      addresses:
      [
        {
          ip: "fc94:f17e:a26b:bc63:f93d:840f:acb8:315d", 
          port: 11811,
        },
      ]
    },
  ]

# InterRobotParticipant:
#   type: "local-discovery-server"

#   id: 1
#   ros-discovery-server: true  # This is equivalent to: guid: "44.53.01.5f.45.50.52.4f.53.49.4d.41"

#   listening-addresses:
#   [
#     {
#       ip: "fc94:1c77:2f76:b88e:464d:84ad:471f:7dce", 
#       port: 11811,
#       transport: "UDP",
#     }
#   ]


