# TL;DR
# docker-compose -f docker-compose.talker.yml up

version: '2.3'

services:

  talker:
    # build: ./docker_image
    image: ghcr.io/dominikn/ros-galactic-fastdds:v2.4.0
    restart: unless-stopped
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    command:
      - bash
      - -c
      - |
          source /fastdds_overlay/install/setup.bash
          ros2 run demo_nodes_cpp talker

  dds-router:
    build: ./docker_image
    restart: unless-stopped
    network_mode: service:husarnet
    volumes:
      - ./dds-router-config.yaml:/config.yaml
    command:
      - bash
      - -c
      - |
          source /DDS-Router/install/setup.bash
          /DDS-Router/install/ddsrouter/bin/ddsrouter -c /config.yaml -r 2

  husarnet:
    image: husarnet/husarnet
    restart: unless-stopped
    volumes:
      - /var/lib/husarnet  # This will persist your Husarnet Client keys, thus IP of the container will be stable/the same between (re)boots
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0  # Husarnet is using IPv6 for the internal connections
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=talker
    env_file:
      - ./.env  # create .env file in the same folder
