# Configuration for a host running a Fast DDS Discovery Server.
#
# 1. It allows service discovery for two other hosts (talker, listener) 
#    in this demo.
# 2. Only the service discovery phase is centralized. After that, ROS 2 
#    nodes communicate p2p.
# 3. You can log messages from a "/chatter" topic using "echo" participant.
#    It is not required however for communication:
#    host-talker --> [/chatter1] --> host-listener
###########################################################################

allowlist:
#   - name: "rt/chatter2"
#     type: "std_msgs::msg::dds_::String_"

echo_participant:
  type: echo

external_partipant:
  type: "local-discovery-server"
  id: 200

  listening-addresses:
    - domain: "dds-discovery-server"  # using hostname instead of Husarnet IPv6 addr
      port: 11811
      transport: "udp"
      
