########################################################
# Husarion Use Case
########################################################

# List of topics that the DDS Router will forward.
# Any topic not included in this list will be blocked by the DDS Router.
# This list can be updated at run time.
allowlist:
  - name: "rt/chatter1"
    type: "std_msgs::msg::dds_::String_"

echo_participant:
  type: echo

external_partipant:
  type: "local-discovery-server"
  id: 200

  listening-addresses:
    - domain: "dds-discovery-server"
      port: 11811
      transport: "udp"
