########################################################
# Husarion Use Case
########################################################

# List of topics that the DDS Router will forward.
# Any topic not included in this list will be blocked by the DDS Router.
# This list can be updated at run time.
allowlist:
  - name: "rt/chatter1"
    type: "std_msgs::msg::dds_::String_"
  # - name: "rt/chatter2"
  #   type: "std_msgs::msg::dds_::String_"

internal_partipant:
  type: local
  domain: 0

external_partipant:
  type: local-discovery-server
  id: 202

  connection-addresses:
    - id: 200
      addresses:
        - domain: "dds-discovery-server"
          port: 11811
          transport: "udp"
          