name: Test DDS Router

on:
  push:
    branches:
      - 'main'
  
jobs:
  test-dds-router:
    runs-on: ubuntu-20.04
    strategy:
      matrix:       
        device-id:         
          - 'ds'        
          - 'listener'
          - 'talker'

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Deploy ${{ matrix.device-id }}
      continue-on-error: true
      timeout-minutes: 1
      run: |
        echo JOINCODE=${{ secrets.HUSARNET_JOINCODE }} > .env
        docker compose -f compose.${{ matrix.device-id }}.yaml up | tee output.txt

    - name: Check if the log contains "Hello World" string
      if: ${{ matrix.device-id }} != "ds"
      run: if [[ $(grep 'Hello World' output.txt | wc -l) -eq 0 ]] && [[ $(grep 'Topic{rt/chatter' output.txt | wc -l) -eq 0 ]]; then exit 1; fi
